import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

describe("listen tts", () => {
  it("keeps expo-speech American English and does not add speech recognition", () => {
    const tts = readFileSync(new URL("./tts.ts", import.meta.url), "utf8");
    const pkg = readFileSync(new URL("../../package.json", import.meta.url), "utf8");
    assert.match(tts, /expo-speech/);
    assert.match(tts, /language:\s*"en-US"/);
    assert.match(tts, /rate:\s*expoSpeechRate/);
    assert.match(tts, /Speech\.stop/);
    assert.doesNotMatch(tts, /expo-speech-recognition/);
    assert.doesNotMatch(pkg, /expo-speech-recognition/);
  });

  it("keeps 听全文 | 复读全文 on top and 单听 + 循环 on each sentence", () => {
    const result = readFileSync(new URL("../screens/ResultScreen.tsx", import.meta.url), "utf8");
    const list = readFileSync(new URL("../components/SentenceList.tsx", import.meta.url), "utf8");
    const hook = readFileSync(new URL("../hooks/useArticleSpeech.ts", import.meta.url), "utf8");
    const planner = readFileSync(new URL("./articleSpeech.ts", import.meta.url), "utf8");
    const speed = readFileSync(new URL("./speechSpeed.ts", import.meta.url), "utf8");
    assert.match(result, /听全文/);
    assert.match(result, /"停止" : "复读全文"/);
    assert.doesNotMatch(result, /"停止" : "复读"/);
    assert.match(result, /停止/);
    assert.match(result, /listenPipe/);
    assert.match(result, /toggle\("loopAll"\)/);
    assert.match(result, /speechSpeedLabel/);
    assert.match(speed, /语速/);
    assert.match(result, /onCycleSpeed/);
    assert.match(result, /restartCurrent/);
    assert.match(result, /speedHold/);
    assert.match(result, /speedDirty/);
    assert.match(result, /peekSpeechSpeed/);
    assert.match(result, /shouldApplyLoadedSpeed/);
    assert.match(result, /setSpeed\(\(prev\) => nextSpeechSpeed\(prev\)\)/);
    assert.doesNotMatch(result, /restartCurrent\(saved\)/);
    assert.doesNotMatch(result, /Slider/);
    assert.match(hook, /currentPlay/);
    assert.match(hook, /modeRef/);
    assert.match(hook, /selectedIdRef\.current/);
    assert.match(hook, /currentPlay\(modeRef\.current, selectedIdRef\.current/);
    assert.match(hook, /return \{ mode, playingId, toggle, start,/);
    assert.doesNotMatch(hook, /playingIdRef/);
    assert.match(hook, /speakAmerican\(item\.text, handlers, speedRef\.current\)/);
    assert.match(hook, /continueSpeaking\(item\.text, handlers, speedRef\.current\)/);
    const homeListen = readFileSync(new URL("../hooks/useHomeArticleListen.ts", import.meta.url), "utf8");
    assert.match(homeListen, /peekSpeechSpeed/);
    assert.match(homeListen, /shouldApplyLoadedSpeed/);
    assert.match(homeListen, /start\("all"\)/);
    assert.doesNotMatch(homeListen, /toggle\("all"\)/);
    assert.doesNotMatch(homeListen, /loadSpeechSpeed\(\)\.then\(setSpeed\)/);
    const lookup = readFileSync(new URL("../screens/LookupScreen.tsx", import.meta.url), "utf8");
    assert.match(lookup, /speakAmerican\(surface,/);
    assert.doesNotMatch(lookup, /loadSpeechSpeed|speechSpeedLabel|restartCurrent/);
    const me = readFileSync(new URL("../screens/MeScreen.tsx", import.meta.url), "utf8");
    assert.doesNotMatch(me, /语速/);
    assert.doesNotMatch(me, /Slider/);
    assert.match(result, /onLoop/);
    assert.match(list, /"停止" : "单听"/);
    assert.doesNotMatch(list, /"停止" : "听"/);
    assert.match(list, /循环/);
    assert.match(list, /停止/);
    assert.match(list, /playingId/);
    assert.match(list, /cardOn/);
    assert.match(hook, /useFocusEffect/);
    assert.match(hook, /AppState/);
    assert.match(hook, /stopSpeaking/);
    assert.match(hook, /loopOne/);
    assert.match(planner, /loopOne/);
    assert.match(result, /stop\(\);\s*openLookup/s);
    assert.doesNotMatch(result, /这句/);
    assert.doesNotMatch(list, /这句/);
    assert.doesNotMatch(result, /单句循环/);
    assert.doesNotMatch(result, /expo-speech-recognition/);
    assert.doesNotMatch(result, /SENTENCE_CAP/);
  });
});
